//+------------------------------------------------------------------+
//|                                              RSI_Divergence.mq5  |
//|                                      Generated by Ninz Signal AI |
//+------------------------------------------------------------------+
#property copyright "Ninz Signal AI"
#property link      "https://ninzsignal.com"
#property version   "1.00"
#property indicator_chart_window
#property indicator_buffers 2
#property indicator_plots   2

#property indicator_label1  "Bullish Divergence"
#property indicator_type1   DRAW_ARROW
#property indicator_color1  clrLimeGreen

#property indicator_label2  "Bearish Divergence"
#property indicator_type2   DRAW_ARROW
#property indicator_color2  clrRed

enum ENUM_DIV_STRENGTH {
    DIV_LOW = 1,    // Low
    DIV_MEDIUM = 2, // Medium
    DIV_HIGH = 3    // High
};

input int                  RSI_Period           = 14;              // RSI Period
input ENUM_APPLIED_PRICE   RSI_Applied_Price    = PRICE_CLOSE;     // RSI Applied Price
input ENUM_DIV_STRENGTH    Div_Strength         = DIV_MEDIUM;      // Divergence Strength
input bool                 ShowHiddenDivergence = false;           // Show Hidden Divergence
input int                  ArrowSize            = 1;               // Arrow Size
input color                BullishColor         = clrLimeGreen;    // Bullish Color
input color                BearishColor         = clrRed;          // Bearish Color
input bool                 EnableSound          = true;            // Enable Sound Alert
input string               SoundFileName        = "sendiri.wav";   // Sound File Name
input bool                 EnablePopup          = true;            // Enable Popup Alert
input bool                 EnablePush           = false;           // Enable Push Notification

double BullBuffer[];
double BearBuffer[];
int rsiHandle;

//+------------------------------------------------------------------+
//| Custom indicator initialization function                         |
//+------------------------------------------------------------------+
int OnInit()
  {
   SetIndexBuffer(0, BullBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(0, PLOT_ARROW, 233); // Up arrow
   PlotIndexSetInteger(0, PLOT_ARROW_SHIFT, ArrowSize);
   PlotIndexSetInteger(0, PLOT_LINE_COLOR, BullishColor);

   SetIndexBuffer(1, BearBuffer, INDICATOR_DATA);
   PlotIndexSetInteger(1, PLOT_ARROW, 234); // Down arrow
   PlotIndexSetInteger(1, PLOT_ARROW_SHIFT, -ArrowSize);
   PlotIndexSetInteger(1, PLOT_LINE_COLOR, BearishColor);

   rsiHandle = iRSI(_Symbol, _Period, RSI_Period, RSI_Applied_Price);
   if(rsiHandle == INVALID_HANDLE) {
      Print("Error creating RSI Handle");
      return INIT_FAILED;
   }

   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Custom indicator iteration function                              |
//+------------------------------------------------------------------+
int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
  {
   if(rates_total < RSI_Period * 2) return 0;
   
   int limit = prev_calculated == 0 ? rates_total - 1 : rates_total - prev_calculated;
   if(prev_calculated == 0) limit = rates_total - 3;
   
   double rsi[];
   ArraySetAsSeries(rsi, true);
   ArraySetAsSeries(low, true);
   ArraySetAsSeries(high, true);
   ArraySetAsSeries(time, true);
   
   ArraySetAsSeries(BullBuffer, true);
   ArraySetAsSeries(BearBuffer, true);
   
   if(CopyBuffer(rsiHandle, 0, 0, limit + 100, rsi) <= 0) return 0;
   
   int periodCheck = 5;
   if (Div_Strength == DIV_LOW) periodCheck = 3;
   else if (Div_Strength == DIV_MEDIUM) periodCheck = 5;
   else if (Div_Strength == DIV_HIGH) periodCheck = 8;
   
   for(int i = limit; i >= 1; i--) {
      BullBuffer[i] = EMPTY_VALUE;
      BearBuffer[i] = EMPTY_VALUE;
      
      // Checking for Pivot Low
      bool isPivotLow = true;
      for(int j = 1; j <= periodCheck; j++) {
         if((i+j < rates_total && low[i] > low[i+j]) || (i-j >= 0 && low[i] >= low[i-j])) {
            isPivotLow = false; break;
         }
      }
      
      if(isPivotLow) {
         // Find previous pivot low
         int prevPivot = -1;
         for(int j = i + periodCheck; j < rates_total - periodCheck; j++) {
            bool isPrevPivotLow = true;
            for(int k = 1; k <= periodCheck; k++) {
               if(low[j] > low[j+k] || low[j] >= low[j-k]) {
                  isPrevPivotLow = false; break;
               }
            }
            if(isPrevPivotLow) { prevPivot = j; break; }
         }
         
         if(prevPivot != -1) {
            // Regular Bullish: Price LL, RSI HL
            if(low[i] < low[prevPivot] && rsi[i] > rsi[prevPivot]) {
               BullBuffer[i] = low[i];
               DrawLine("BullDiv", time[prevPivot], low[prevPivot], time[i], low[i], BullishColor);
               TriggerAlert("Bullish Regular Divergence");
            }
            // Hidden Bullish: Price HL, RSI LL
            else if(ShowHiddenDivergence && low[i] > low[prevPivot] && rsi[i] < rsi[prevPivot]) {
               BullBuffer[i] = low[i];
               DrawLine("BullHiddenDiv", time[prevPivot], low[prevPivot], time[i], low[i], BullishColor);
               TriggerAlert("Bullish Hidden Divergence");
            }
         }
      }
      
      // Checking for Pivot High
      bool isPivotHigh = true;
      for(int j = 1; j <= periodCheck; j++) {
         if((i+j < rates_total && high[i] < high[i+j]) || (i-j >= 0 && high[i] <= high[i-j])) {
            isPivotHigh = false; break;
         }
      }
      
      if(isPivotHigh) {
         // Find previous pivot high
         int prevPivotHigh = -1;
         for(int j = i + periodCheck; j < rates_total - periodCheck; j++) {
            bool isPrevPivotHigh = true;
            for(int k = 1; k <= periodCheck; k++) {
               if(high[j] < high[j+k] || high[j] <= high[j-k]) {
                  isPrevPivotHigh = false; break;
               }
            }
            if(isPrevPivotHigh) { prevPivotHigh = j; break; }
         }
         
         if(prevPivotHigh != -1) {
            // Regular Bearish: Price HH, RSI LH
            if(high[i] > high[prevPivotHigh] && rsi[i] < rsi[prevPivotHigh]) {
               BearBuffer[i] = high[i];
               DrawLine("BearDiv", time[prevPivotHigh], high[prevPivotHigh], time[i], high[i], BearishColor);
               TriggerAlert("Bearish Regular Divergence");
            }
            // Hidden Bearish: Price LH, RSI HH
            else if(ShowHiddenDivergence && high[i] < high[prevPivotHigh] && rsi[i] > rsi[prevPivotHigh]) {
               BearBuffer[i] = high[i];
               DrawLine("BearHiddenDiv", time[prevPivotHigh], high[prevPivotHigh], time[i], high[i], BearishColor);
               TriggerAlert("Bearish Hidden Divergence");
            }
         }
      }
   }
   
   return(rates_total);
  }

void DrawLine(string prefix, datetime time1, double price1, datetime time2, double price2, color clr) {
   string objName = prefix + "_" + TimeToString(time1) + "_" + TimeToString(time2);
   if(ObjectFind(0, objName) < 0) {
      ObjectCreate(0, objName, OBJ_TREND, 0, time1, price1, time2, price2);
      ObjectSetInteger(0, objName, OBJPROP_COLOR, clr);
      ObjectSetInteger(0, objName, OBJPROP_STYLE, STYLE_DOT);
      ObjectSetInteger(0, objName, OBJPROP_WIDTH, 1);
      ObjectSetInteger(0, objName, OBJPROP_RAY_RIGHT, false);
   }
}

datetime lastAlertTime = 0;
void TriggerAlert(string msg) {
   if(TimeCurrent() - lastAlertTime < 60) return; // Prevent alert spam
   string fullMsg = _Symbol + " (" + EnumToString((ENUM_TIMEFRAMES)Period()) + ") - " + msg;
   
   if(EnablePopup) Alert(fullMsg);
   if(EnablePush) SendNotification(fullMsg);
   if(EnableSound) PlaySound(SoundFileName);
   
   lastAlertTime = TimeCurrent();
}
//+------------------------------------------------------------------+
